# Generated by Django 3.2.2 on 2021-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password_1', models.CharField(max_length=400)),
                ('password_2', models.CharField(max_length=400)),
            ],
        ),
    ]
